
let n = 5;
const n2 = 9;
const s = '8';
const s2 = 'sky';
const b = true;
const u = undefined;
const nu = null;

console.log(`${typeof n} + ${typeof n2} = ${n + n2} (${typeof (n + n2)})`);
console.log( n + s);
console.log(n + b);
console.log(n + u);
console.log(n + nu);
console.log(s2 + b);
console.log('--------------');
console.log(s - s2);
console.log(b - nu);
console.log(s - n);
console.log('--------------*');
console.log(n * s2);
console.log(n * b);
console.log(b * nu);
console.log('--------------/');
console.log(n / nu);
console.log(n / s);
console.log('--------------%');
console.log(n2 % n);
console.log(n % n2);
console.log('--------------**');
console.log(n ** 3);
console.log(n ** n2);
console.log('--------------+-=');
n = 2;
console.log(n += n);
console.log(n += n);
console.log(n -= n);
console.log('--------------++--');
n = 5;
n = ++n;
console.log(n);
n = ++n;
console.log(n);
n = --n;
console.log(n);
n = --n;
console.log(n);
